language: go
go:
  - 1.3
before_script:
  - npm install
  - npm install -g grunt-cli
  - echo 'America/Montreal' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
script:
  - grunt
  - go test -v ./...
